before:
  hooks:
    - go mod tidy
    - go fmt ./...
builds:
  - main: ./as212510.net
    binary: as212510.net
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:{{ .Version }}-amd64"
      - "{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.authors=Ludovic Ortega <ludovic.ortega@adminafk.fr>"
      - "--label=org.opencontainers.image.url={{ .Env.SOURCE_URL }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:{{ .Version }}-arm64"
      - "{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.authors=Ludovic Ortega <ludovic.ortega@adminafk.fr>"
      - "--label=org.opencontainers.image.url={{ .Env.SOURCE_URL }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:latest'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:latest-amd64'
      - '{{ .Env.REGISTRY }}/{{ tolower .Env.REPOSITORY }}:latest-arm64'
checksum:
  name_template: sha256sums.txt
source:
  enabled: true