[project]
name = "as212510.net"
revision = "1.0"

[profiles.default]
AS212510_NET_MIKROTIK_ADDRESS = { description = "AS212510_NET_MIKROTIK_ADDRESS secret", required = true }
AS212510_NET_MIKROTIK_USERNAME = { description = "AS212510_NET_MIKROTIK_USERNAME secret", required = true }
AS212510_NET_MIKROTIK_PASSWORD = { description = "AS212510_NET_MIKROTIK_PASSWORD secret", required = true }
